version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/apache-reverse-proxy"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/apache-server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/net-runtime-7-0"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/net-sdk-7-0"
    schedule:
      interval: "monthly"      