version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/apache-server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/redmine"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/sonarqube"
    schedule:
      interval: "monthly"