kind: pipeline
name: docker-custom-images

steps:
- name: apache-reverse-proxy
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/apache-reverse-proxy
    dockerfile: apache-reverse-proxy/Dockerfile
    dry_run: true
    purge: false

- name: netcore-sdk-3-1
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/netcore-sdk-3-1
    dockerfile: netcore-sdk-3-1/Dockerfile
    dry_run: true
    purge: false

- name: netcore-runtime-3-1
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/netcore-runtime-3-1
    dockerfile: netcore-runtime-3-1/Dockerfile
    dry_run: true
    purge: false

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock