kind: pipeline
name: docker-custom-images

steps:
- name: apache-reverse-proxy
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/apache-reverse-proxy
    dockerfile: apache-reverse-proxy/Dockerfile
    dry_run: true
    purge: false

- name: apache-server
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/apache-server
    dockerfile: apache-server/Dockerfile
    dry_run: true
    purge: false

- name: net-sdk-5-0
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/net-sdk-5-0
    dockerfile: net-sdk-5-0/Dockerfile
    dry_run: true
    purge: false

- name: net-runtime-5-0
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/net-runtime-5-0
    dockerfile: net-runtime-5-0/Dockerfile
    dry_run: true
    purge: false

- name: net-sdk-6-0
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/net-sdk-6-0
    dockerfile: net-sdk-6-0/Dockerfile
    dry_run: true
    purge: false

- name: net-runtime-6-0
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/net-runtime-6-0
    dockerfile: net-runtime-6-0/Dockerfile
    dry_run: true
    purge: false

- name: vpn-server
  image: plugins/docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  settings:
    repo: dysnomia/vpn-server
    dockerfile: vpn-server/Dockerfile
    dry_run: true
    purge: false

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock